/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasNoticiaIdRouteImport } from './routes/noticias.$noticiaId'
import { Route as ApiPublicMediosSplatRouteImport } from './routes/api/public/medios/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasNoticiaIdRoute = NoticiasNoticiaIdRouteImport.update({
  id: '/noticias/$noticiaId',
  path: '/noticias/$noticiaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediosSplatRoute = ApiPublicMediosSplatRouteImport.update({
  id: '/api/public/medios/$',
  path: '/api/public/medios/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/staff': typeof StaffRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/noticias/$noticiaId': typeof NoticiasNoticiaIdRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/api/public/medios/$': typeof ApiPublicMediosSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/staff': typeof StaffRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/noticias/$noticiaId': typeof NoticiasNoticiaIdRoute
  '/noticias': typeof NoticiasIndexRoute
  '/api/public/medios/$': typeof ApiPublicMediosSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/staff': typeof StaffRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/noticias/$noticiaId': typeof NoticiasNoticiaIdRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/api/public/medios/$': typeof ApiPublicMediosSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/login'
    | '/proyectos'
    | '/staff'
    | '/admin'
    | '/noticias/$noticiaId'
    | '/noticias/'
    | '/api/public/medios/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/login'
    | '/proyectos'
    | '/staff'
    | '/admin'
    | '/noticias/$noticiaId'
    | '/noticias'
    | '/api/public/medios/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contacto'
    | '/login'
    | '/proyectos'
    | '/staff'
    | '/_authenticated/admin'
    | '/noticias/$noticiaId'
    | '/noticias/'
    | '/api/public/medios/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  ProyectosRoute: typeof ProyectosRoute
  StaffRoute: typeof StaffRoute
  NoticiasNoticiaIdRoute: typeof NoticiasNoticiaIdRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  ApiPublicMediosSplatRoute: typeof ApiPublicMediosSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$noticiaId': {
      id: '/noticias/$noticiaId'
      path: '/noticias/$noticiaId'
      fullPath: '/noticias/$noticiaId'
      preLoaderRoute: typeof NoticiasNoticiaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/medios/$': {
      id: '/api/public/medios/$'
      path: '/api/public/medios/$'
      fullPath: '/api/public/medios/$'
      preLoaderRoute: typeof ApiPublicMediosSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  ProyectosRoute: ProyectosRoute,
  StaffRoute: StaffRoute,
  NoticiasNoticiaIdRoute: NoticiasNoticiaIdRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  ApiPublicMediosSplatRoute: ApiPublicMediosSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
